package com.mikosik.stork.test.cases;

import static com.mikosik.stork.test.SnippetSuite.snippetSuite;
import static org.quackery.Suite.suite;

import org.quackery.Test;

public class TestStream {
  public static Test testStream() {
    return suite("stream")
        .add(snippetSuite("constructor")
            .importing("lang.stream.some")
            .importing("lang.stream.none")
            .test("some(120)(some(121)(some(122)(none)))", "xyz")
            .test("none", ""))
        .add(snippetSuite("hasSome")
            .importing("lang.stream.hasSome")
            .importing("lang.stream.some")
            .importing("lang.stream.none")
            .test("hasSome(none)", false)
            .test("hasSome(some(1)(none))", true)
            .test("hasSome(some(1)(some(2)(some(3)(none))))", true))
        .add(snippetSuite("hasNone")
            .importing("lang.stream.hasNone")
            .importing("lang.stream.some")
            .importing("lang.stream.none")
            .test("hasNone(none)", true)
            .test("hasNone(some(1)(none))", false)
            .test("hasNone(some(1)(some(2)(some(3)(none))))", false))
        .add(snippetSuite("equal")
            .importing("lang.stream.some")
            .importing("lang.stream.none")
            .importing("lang.stream.equal")
            .importing("lang.integer.equal eq")
            .test("equal(eq)('')('')", true)
            .test("equal(eq)('a')('a')", true)
            .test("equal(eq)('ab')('ab')", true)
            .test("equal(eq)('abc')('abc')", true)
            .test("equal(eq)('a')('')", false)
            .test("equal(eq)('')('a')", false)
            .test("equal(eq)('a')('b')", false)
            .test("equal(eq)('ab')('a')", false)
            .test("equal(eq)('a')('ab')", false)
            .test("equal(eq)('ab')('ac')", false)
            .test("equal(eq)('abc')('ab')", false)
            .test("equal(eq)('ab')('abc')", false)
            .test("equal(eq)('abc')('abd')", false))
        .add(snippetSuite("single")
            .importing("lang.stream.single")
            .test("single(120)", "x"))
        .add(snippetSuite("repeat")
            .importing("lang.stream.repeat")
            .importing("lang.stream.limit")
            .test("limit(5)(repeat(120))", "xxxxx"))
        .add(snippetSuite("cycle")
            .importing("lang.stream.cycle")
            .importing("lang.stream.limit")
            .test("limit(10)(cycle('abc'))", "abcabcabca")
            .test("limit(10)(cycle('a'))", "aaaaaaaaaa")
            .test("cycle('')", ""))
        .add(snippetSuite("array")
            .importing("lang.stream.array")
            .importing("lang.stream.limit")
            .test("array(0)", "")
            .test("array(1)(97)", "a")
            .test("array(2)(97)(98)", "ab")
            .test("array(3)(97)(98)(99)", "abc"))
        .add(snippetSuite("generate")
            .importing("lang.stream.generate")
            .importing("lang.stream.limit")
            .importing("lang.integer.add")
            .test("limit(10)(generate(add(1))(97))", "abcdefghij"))
        .add(snippetSuite("prepend")
            .importing("lang.stream.prepend")
            .test("prepend('x')('abc')", "xabc")
            .test("prepend('x')('')", "x"))
        .add(snippetSuite("append")
            .importing("lang.stream.append")
            .test("append('x')('abc')", "abcx")
            .test("append('x')('')", "x"))
        .add(snippetSuite("reverse")
            .importing("lang.stream.reverse")
            .test("reverse('abcde')", "edcba")
            .test("reverse('')", ""))
        .add(snippetSuite("each")
            .importing("lang.stream.each")
            .importing("lang.integer.add")
            .test("each(add(1))('ace')", "bdf")
            .test("each(add(1))('')", ""))
        .add(snippetSuite("filter")
            .importing("lang.stream.filter")
            .importing("lang.integer.moreThan")
            .test("filter(moreThan(100))('axbycz')", "xyz")
            .test("filter(moreThan(100))('xyz')", "xyz")
            .test("filter(moreThan(100))('')", ""))
        .add(snippetSuite("limit")
            .importing("lang.stream.limit")
            .test("limit(5)('abcde')", "abcde")
            .test("limit(4)('abcde')", "abcd")
            .test("limit(6)('abcde')", "abcde")
            .test("limit(0)('abcde')", "")
            .test("limit(0)('')", ""))
        .add(snippetSuite("skip")
            .importing("lang.stream.skip")
            .test("skip(4)('abcde')", "e")
            .test("skip(5)('abcde')", "")
            .test("skip(6)('abcde')", "")
            .test("skip(0)('abcde')", "abcde")
            .test("skip(-1)('abcde')", "abcde"))
        .add(snippetSuite("while")
            .importing("lang.stream.while")
            .importing("lang.integer.lessThan")
            .test("while(lessThan(110))('abcde')", "abcde")
            .test("while(lessThan(110))('xabcde')", "")
            .test("while(lessThan(110))('abcxde')", "abc")
            .test("while(lessThan(110))('abcdex')", "abcde")
            .test("while(lessThan(110))('x')", "")
            .test("while(lessThan(110))('')", ""))
        .add(snippetSuite("for")
            .importing("lang.stream.for")
            .importing("lang.integer.add")
            .importing("lang.integer.lessThan")
            .test("for(97)(lessThan(107))(add(1))", "abcdefghij")
            .test("for(97)(lessThan(97))(add(1))", ""))
        .add(snippetSuite("reduce")
            .importing("lang.stream.reduce")
            .importing("lang.stream.append")
            .importing("lang.stream.some")
            .importing("lang.stream.none")
            .test("reduce('a')(append)(some('x')(some('y')(some('z')(none))))", "axyz")
            .test("reduce('')(append)(none)", ""))
        .add(snippetSuite("flatten")
            .importing("lang.stream.flatten")
            .importing("lang.stream.some")
            .importing("lang.stream.none")
            .importing("lang.stream.limit")
            .importing("lang.stream.repeat")
            .test("flatten(some('abc')(some('de')(some('f')(none))))", "abcdef")
            .test("flatten(some('abc')(none))", "abc")
            .test("flatten(some('')(some('')(some('')(none))))", "")
            .test("flatten(some('')(none))", "")
            .test("flatten(some('abc')(some('')(some('def')(none))))", "abcdef")
            .test("flatten(none)", "")
            .test("limit(5)(flatten(repeat('x')))", "xxxxx"))
        .add(snippetSuite("contains")
            .importing("lang.integer.equal")
            .importing("lang.stream.contains")
            .test("contains(equal(0))('xyz')", false)
            .test("contains(equal(120))('xyz')", true))
        .add(snippetSuite("tryAt")
            .importing("lang.stream.tryAt")
            .importing("lang.stream.some")
            .importing("lang.stream.none")
            // TODO fix index out of bounds
            // .test("tryAt(-1)(some(10)(some(20)(some(30)(none))))((x){x})(99)", "99")
            .test("tryAt(0)(some(10)(some(20)(some(30)(none))))((x){x})(99)", 10)
            .test("tryAt(1)(some(10)(some(20)(some(30)(none))))((x){x})(99)", 20)
            .test("tryAt(2)(some(10)(some(20)(some(30)(none))))((x){x})(99)", 30)
            .test("tryAt(3)(some(10)(some(20)(some(30)(none))))((x){x})(99)", 99)
            .test("tryAt(0)(none)((x){x})(99)", 99))
        .add(snippetSuite("tryFirst")
            .importing("lang.stream.tryFirst")
            .importing("lang.stream.some")
            .importing("lang.stream.none")
            .test("tryFirst(some(10)(some(20)(some(30)(none))))((x){x})(99)", 10)
            .test("tryFirst(none)((x){x})(99)", 99))
        .add(snippetSuite("length")
            .importing("lang.stream.length")
            .test("length('')", 0)
            .test("length('xyz')", 3))
        .add(snippetSuite("count")
            .importing("lang.stream.count")
            .importing("lang.stream.limit")
            .importing("lang.stream.each")
            .importing("lang.integer.add")
            .test("each(add(97))(limit(5)(count))", "abcde"))
        .add(snippetSuite("countFrom")
            .importing("lang.stream.countFrom")
            .importing("lang.stream.limit")
            .test("limit(5)(countFrom(97))", "abcde"));
  }
}
