package com.mikosik.stork;

import static com.mikosik.stork.StorkTest.storkTest;
import static org.quackery.Suite.suite;

import org.quackery.Suite;

public class TestBooleanLibrary {
  public static Suite testBooleanLibrary() {
    return suite("test boolean library")
        .add(suite("true/false")
            .add(storkTest("true(then)(else) = then")
                .givenImported("boolean.stork")
                .given("main{true(1)(2)}")
                .when("main")
                .thenReturned("1"))
            .add(storkTest("false(then)(else) = else")
                .givenImported("boolean.stork")
                .given("main{false(1)(2)}")
                .when("main")
                .thenReturned("2")))
        .add(suite("not")
            .add(storkTest("not(true) = false")
                .givenImported("boolean.stork")
                .given("main{not(true)}")
                .when("main")
                .thenReturned("false"))
            .add(storkTest("not(false) = true")
                .givenImported("boolean.stork")
                .given("main{not(false)}")
                .when("main")
                .thenReturned("true")))
        .add(suite("and")
            .add(storkTest("and(true)(true) = true")
                .givenImported("boolean.stork")
                .given("main{and(true)(true)}")
                .when("main")
                .thenReturned("true"))
            .add(storkTest("and(false)(true) = false")
                .givenImported("boolean.stork")
                .given("main{and(false)(true)}")
                .when("main")
                .thenReturned("false"))
            .add(storkTest("and(true)(false) = false")
                .givenImported("boolean.stork")
                .given("main{and(true)(false)}")
                .when("main")
                .thenReturned("false"))
            .add(storkTest("and(false)(false) = false")
                .givenImported("boolean.stork")
                .given("main{and(false)(false)}")
                .when("main")
                .thenReturned("false")))
        .add(suite("or")
            .add(storkTest("or(true)(true) = true")
                .givenImported("boolean.stork")
                .given("main{or(true)(true)}")
                .when("main")
                .thenReturned("true"))
            .add(storkTest("or(false)(true) = true")
                .givenImported("boolean.stork")
                .given("main{or(false)(true)}")
                .when("main")
                .thenReturned("true"))
            .add(storkTest("or(true)(false) = true")
                .givenImported("boolean.stork")
                .given("main{or(true)(false)}")
                .when("main")
                .thenReturned("true"))
            .add(storkTest("or(false)(false) = false")
                .givenImported("boolean.stork")
                .given("main{or(false)(false)}")
                .when("main")
                .thenReturned("false")));
  }
}
