package com.mikosik.stork;

import static com.mikosik.stork.Snippet.snippet;
import static org.quackery.Suite.suite;

import org.quackery.Suite;

public class TestBooleanLibrary {
  public static Suite testBooleanLibrary() {
    return suite("test boolean library")
        .add(suite("true/false")
            .add(snippet("true(then)(else) = then")
                .include("boolean.stork")
                .define("main{true(1)(2)}")
                .launch("main")
                .expect("1"))
            .add(snippet("false(then)(else) = else")
                .include("boolean.stork")
                .define("main{false(1)(2)}")
                .launch("main")
                .expect("2")))
        .add(suite("not")
            .add(snippet("not(true) = false")
                .include("boolean.stork")
                .define("main{not(true)}")
                .launch("main")
                .expect("false"))
            .add(snippet("not(false) = true")
                .include("boolean.stork")
                .define("main{not(false)}")
                .launch("main")
                .expect("true")))
        .add(suite("and")
            .add(snippet("and(true)(true) = true")
                .include("boolean.stork")
                .define("main{and(true)(true)}")
                .launch("main")
                .expect("true"))
            .add(snippet("and(false)(true) = false")
                .include("boolean.stork")
                .define("main{and(false)(true)}")
                .launch("main")
                .expect("false"))
            .add(snippet("and(true)(false) = false")
                .include("boolean.stork")
                .define("main{and(true)(false)}")
                .launch("main")
                .expect("false"))
            .add(snippet("and(false)(false) = false")
                .include("boolean.stork")
                .define("main{and(false)(false)}")
                .launch("main")
                .expect("false")))
        .add(suite("or")
            .add(snippet("or(true)(true) = true")
                .include("boolean.stork")
                .define("main{or(true)(true)}")
                .launch("main")
                .expect("true"))
            .add(snippet("or(false)(true) = true")
                .include("boolean.stork")
                .define("main{or(false)(true)}")
                .launch("main")
                .expect("true"))
            .add(snippet("or(true)(false) = true")
                .include("boolean.stork")
                .define("main{or(true)(false)}")
                .launch("main")
                .expect("true"))
            .add(snippet("or(false)(false) = false")
                .include("boolean.stork")
                .define("main{or(false)(false)}")
                .launch("main")
                .expect("false")));
  }
}
