#!/bin/bash -e

HERE=`dirname ${0}`
cd "${HERE}/.."

java \
 --add-opens=java.base/java.lang=ALL-UNNAMED \
 --add-opens=java.base/java.util=ALL-UNNAMED \
 --add-opens=java.base/java.math=ALL-UNNAMED \
 --add-opens=java.base/java.lang.ref=ALL-UNNAMED \
 --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED \
 -cp jar/quackery-0.17.0.jar:jar/logbuddy-0.19.1.jar \
 java/com/mikosik/stork/test/RunTests.java
